---
title: "Diagrama de dispersión con el dataset MPG"
author: "Carlos Lesmes"
date: "`r Sys.Date()`"
format:
  html:
    theme: materia
    toc: true
    toc_float: true
    number-sections: true
    code-fold: show
    df-print: kable
lang : es
---

```{r}
library(ggplot2)
suppressPackageStartupMessages(library(dplyr))
data("mpg")
```

# Diagrama de dispersión con todo ggplot2

```{r}
ggplot(mpg, aes(x=displ, y=hwy)) +
  geom_point(aes(color=class), size=3) +  
  labs(
    title = "Cilindrada vs. Rendimiento en autopista", 
    x = "Cilindrada (Litros)", 
    y = "Rendimiento en autopista  (millas por galón)", 
    color = "Clase de vehículo",
    caption = "Fuente R"
  ) +
  theme_minimal() +  
  theme(
    axis.title.x = element_text(size=14, family="Arial", color="darkblue"),
    axis.title.y = element_text(size=14, family="Arial", color="darkblue"),
    axis.text.x = element_text(size=12, family="Arial", color="black"),
    axis.text.y = element_text(size=12, family="Arial", color="black"),
    plot.title = element_text(size=16, family="Arial", hjust = 0.5, color="darkred"),
    legend.title = element_text(size=12, family="Arial", color="darkblue"),
    legend.text = element_text(size=10, family="Arial", color="black"),
    axis.ticks = element_line(color = 2, linewidth = 2),
    scale_y_continuous(breaks = seq(0, 60, by = 10)),
    axis.line = element_line(color = "red", linewidth = 1.5,linetype = 2)
    )
```

