---
title: El YAML
author: Carlos Lesmes
date: "`r Sys.Date()`"
format:
  html:
    theme: journal
    toc: true
    toc_float: true
    number-sections: true
    code-fold: show
    embed-resources: true
lang : es
---

# El YAML

El YAML de este documento es el encabezado del documento `.qmd` antes de *renderizarlo*[^1]. Estas son las opciones `yaml` del documento, es decir los metadatos[^2] del escrito. Al escribirlo se debe respetar la indentación, se encuentra separado al inicio del documento por tres guiones al comienzo y tres guiones al final. Para saber más vea [aquí](https://www.ibm.com/es-es/think/topics/yaml).

[^1]: render: the process of converting code into viewable, interactive web content

[^2]: datos de los datos

```         
---
title: El YAML
author: Carlos Lesmes
date: "`r Sys.Date()`"
format:
   html:
       theme: journal
       toc: true
       toc_float: true
       number-sections: true
       code-fold: show
lang : es
---
```

Vea más información del YAML [aquí](https://rpubs.com/gustavomtzv/874870)

## `title`, `author` y `date`

Son respectivamente el título, el autor y la fecha del documento. Dejar un espacio después de los dos puntos y escribir los datos deseados. Las palabras clave `title`, `author` y `date` no se deben cambiar.

## `format`

Aquí se especifíca el formato de salida del documento, en este caso `html`. Dentro de html están las siguientes opciones:

1.  theme: journal
2.  toc: true
3.  toc_float: true
4.  number-sections: true
5.  code-fold: show

La opción `theme` permite escoger un color específico para los títulos, enlaces, etc. Puede cambiar el tema `journal` por otros 24 que encontrará en [Temas](https://quarto.org/docs/output-formats/html-themes.html).

## `toc` y `toc-float` 
Muestran respectivamente la tabla de contenido y la mantiene siempre visible con la opción `true`. Si no se desea que lo hagan use `false`.

## `number-sections` y `code-fold`
Enumera los títulos y subtítulos y `code-fold` permite ver y ocultar el código R en el documento haciendo clic en el triángulo-Código a continuación:

```{r}
m = matrix(1:16,nrow = 4)
m
```
El elemento (2,2) de la matriz es `r m[2,2]`.

Por último, para que las opciones salgan en español use `lang: es`. Los tags para ingles, francés y alemán son respectivamente `en`, `fr` y `de`.

Recuerde que se debe respetar la indentación, es decir, la sangría.

## Un ejemplo de otro `yaml`

```
---
author: Carlos lesmes
title: Primer documento
date: "`r Sys.Date()`"
format: 
  html:
    code-fold: true
    embed-resources: true
toc: true
lang: "es"
number-sections: true
theme:
  light: flatly
  dark: darkly
warning: false
bibliography: biblio.bib
---
```
En este caso 

`
theme:
  light: flatly
  dark: darkly
`
permite cambiar el documento de light(blanco) a dark(negro). La opción `warining: false` no imprime los warnings generados por `R`. 

El archivo de bibliografía que acompaña al documento debe tener el nombre `biblio.bib`.